### ISSUE TITLE
请使用 MIT 开源协议

### ISSUE THREAD

**Issue by KeJunMao** [uni-helper/galanga#16]
### 描述问题

如题， @censujiang 

### 复现

不适用

### 系统信息

```Shell
不适用
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by censujiang** [comment]
源项目使用apache2.0协议，如果此时使用MIT协议会有违反原项目协议的嫌疑
